"""Render a trace as a self-contained HTML page.

The output is a single file with all CSS + JS inlined. No
external dependencies, no CDN, no analytics. Drop it on disk
and email it; it works offline.

The page renders the trace as a tree (collapsible per branch),
highlights ERROR spans in red, and shows the input/output of
each span on demand. It's deliberately minimal — the goal is
"share with a teammate" rather than "production dashboard."
"""

from __future__ import annotations

import html
import json
from datetime import UTC, datetime
from pathlib import Path

from clew.core.models import Span, SpanStatus, Trace

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>clew trace {trace_id}</title>
<style>
  :root {{
    --bg: #0d1117; --fg: #c9d1d9; --muted: #8b949e;
    --accent: #58a6ff; --error: #f85149; --ok: #3fb950;
    --border: #30363d; --row: #161b22;
  }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         background: var(--bg); color: var(--fg);
         margin: 0; padding: 24px; line-height: 1.5; }}
  h1 {{ color: var(--accent); margin: 0 0 4px; font-size: 1.4em; }}
  h2 {{ margin-top: 32px; font-size: 1.1em; border-bottom: 1px solid var(--border);
        padding-bottom: 4px; }}
  .meta {{ color: var(--muted); font-size: 0.9em; margin-bottom: 16px; }}
  .meta code {{ background: var(--row); padding: 2px 6px; border-radius: 3px; }}
  ul.tree, ul.tree ul {{ list-style: none; padding-left: 20px; }}
  ul.tree {{ padding-left: 0; }}
  .span {{ border: 1px solid var(--border); border-radius: 6px;
           padding: 8px 12px; margin: 4px 0; background: var(--row); }}
  .span.error {{ border-color: var(--error); }}
  .span-head {{ display: flex; gap: 8px; align-items: center;
                cursor: pointer; user-select: none; }}
  .caret {{ color: var(--muted); width: 1em; }}
  .name {{ font-weight: 600; }}
  .type {{ color: var(--muted); font-size: 0.85em;
           background: var(--bg); padding: 1px 6px; border-radius: 3px; }}
  .status-ok {{ color: var(--ok); font-size: 0.85em; }}
  .status-error {{ color: var(--error); font-size: 0.85em; font-weight: 600; }}
  .id {{ color: var(--muted); font-size: 0.75em; font-family: monospace; }}
  .duration {{ color: var(--muted); font-size: 0.85em; margin-left: auto; }}
  .details {{ margin-top: 8px; padding: 8px 12px;
              background: var(--bg); border-radius: 4px; display: none; }}
  .details.open {{ display: block; }}
  .details pre {{ overflow-x: auto; white-space: pre-wrap;
                  word-wrap: break-word; max-width: 100%;
                  font-size: 0.85em; margin: 4px 0; }}
  .label {{ color: var(--muted); font-size: 0.8em;
            text-transform: uppercase; letter-spacing: 0.05em; }}
  .controls {{ margin: 16px 0; }}
  .controls button {{ background: var(--row); color: var(--fg);
                     border: 1px solid var(--border); padding: 4px 10px;
                     border-radius: 4px; cursor: pointer; margin-right: 8px; }}
  .controls button:hover {{ border-color: var(--accent); }}
</style>
</head>
<body>
<h1>clew trace <span class="id">{trace_id}</span></h1>
<div class="meta">
  root: <code>{root_id}</code> · spans: <strong>{span_count}</strong> ·
  errors: <strong>{error_count}</strong> · started: {started_at}
</div>
<div class="controls">
  <button onclick="document.querySelectorAll('.details').forEach(e => e.classList.add('open'))">Expand all</button>
  <button onclick="document.querySelectorAll('.details').forEach(e => e.classList.remove('open'))">Collapse all</button>
</div>
<ul class="tree">
{html_tree}
</ul>
<hr style="margin: 32px 0; border: none; border-top: 1px solid var(--border);">
<p class="meta">
  Generated by <a href="https://github.com/clew/clew" style="color: var(--accent);">clew</a> ·
  <span class="id">{generated_at}</span>
</p>
<script>
document.querySelectorAll('.span-head').forEach(head => {{
  head.addEventListener('click', () => {{
    const d = head.nextElementSibling;
    if (d && d.classList.contains('details')) {{
      d.classList.toggle('open');
    }}
    const caret = head.querySelector('.caret');
    if (caret) {{
      caret.textContent = d && d.classList.contains('open') ? '▼' : '▶';
    }}
  }});
}});
</script>
</body>
</html>
"""


def _format_span(s: Span) -> str:
    """Render a single span as HTML."""
    duration_ms = 0.0
    if s.started_at and s.ended_at:
        delta = (s.ended_at - s.started_at).total_seconds() * 1000
        duration_ms = max(0, delta)
    err_class = " error" if s.status is SpanStatus.ERROR else ""
    status_class = "status-error" if s.status is SpanStatus.ERROR else "status-ok"
    caret = "▶"
    parts: list[str] = []
    parts.append(f'<li><div class="span{err_class}">')
    parts.append(
        f'<div class="span-head"><span class="caret">{caret}</span>'
        f'<span class="name">{html.escape(s.name)}</span>'
        f'<span class="type">{html.escape(s.type.value)}</span>'
        f'<span class="{status_class}">{html.escape(s.status.value)}</span>'
        f'<span class="duration">{duration_ms:.1f}ms</span></div>'
    )
    parts.append('<div class="details">')
    parts.append(
        f'<div class="label">id</div><div class="id">{html.escape(s.id)}</div>'
    )
    if s.parent_ids:
        parts.append(
            f'<div class="label">parent_ids</div>'
            f'<div class="id">{html.escape(", ".join(s.parent_ids))}</div>'
        )
    if s.error:
        parts.append(
            f'<div class="label">error</div>'
            f'<pre>{html.escape(s.error)}</pre>'
        )
    if s.attributes:
        parts.append(
            f'<div class="label">attributes</div>'
            f'<pre>{html.escape(json.dumps(s.attributes, indent=2, default=str))}</pre>'
        )
    if s.input is not None:
        parts.append(
            f'<div class="label">input</div>'
            f'<pre>{html.escape(_stringify(s.input))}</pre>'
        )
    if s.output is not None:
        parts.append(
            f'<div class="label">output</div>'
            f'<pre>{html.escape(_stringify(s.output))}</pre>'
        )
    if s.metadata:
        parts.append(
            f'<div class="label">metadata</div>'
            f'<pre>{html.escape(json.dumps(s.metadata, indent=2, default=str))}</pre>'
        )
    parts.append("</div></div>")
    return "\n".join(parts)


def _stringify(value: object) -> str:
    """Best-effort string repr for input/output."""
    if isinstance(value, str):
        return value
    try:
        return json.dumps(value, indent=2, default=str)
    except (TypeError, ValueError):
        return repr(value)


def render_html(trace: Trace) -> str:
    """Render a :class:`Trace` as a self-contained HTML page.

    The output uses a collapsible tree: every span is a clickable
    card that reveals its input / output / metadata on demand.
    ERROR spans get a red border so they stand out.
    """
    # Build a parent -> children map.
    children: dict[str, list[Span]] = {}
    by_id = {s.id: s for s in trace.spans}
    for s in trace.spans:
        for parent in s.parent_ids:
            children.setdefault(parent, []).append(s)
    # Order children by started_at for stability.
    for k in children:
        children[k].sort(key=lambda s: s.started_at or _MIN)

    def _render_subtree(span_id: str) -> str:
        s = by_id[span_id]
        kids = children.get(span_id, [])
        parts = [_format_span(s)]
        if kids:
            parts.append("<ul>")
            for c in kids:
                parts.append(_render_subtree(c.id))
            parts.append("</ul>")
        return "\n".join(parts)

    root = next((s for s in trace.spans if s.id == trace.root_span_id), None)
    if root is None and trace.spans:
        root = trace.spans[0]
    html_tree = "<li>(empty trace)</li>" if root is None else _render_subtree(root.id)
    started = root.started_at.isoformat() if root and root.started_at else "?"
    return _TEMPLATE.format(
        trace_id=html.escape(trace.trace_id[:16] or trace.trace_id),
        root_id=html.escape(trace.root_span_id[:16] or trace.root_span_id),
        span_count=len(trace.spans),
        error_count=sum(1 for s in trace.spans if s.status is SpanStatus.ERROR),
        started_at=html.escape(started),
        html_tree=html_tree,
        generated_at=html.escape(_now()),
    )


def write_html(trace: Trace, out: Path) -> Path:
    """Render the trace to ``out`` and return ``out``.

    The file is self-contained: drop it in an email, an S3 bucket,
    or a GitHub gist; the recipient can open it in any browser.
    """
    out.write_text(render_html(trace), encoding="utf-8")
    return out


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


_MIN = datetime.min.replace(tzinfo=UTC)


def _now() -> str:
    return datetime.now(UTC).isoformat()


__all__ = ["render_html", "write_html"]
